spring.application.name=music

spring.config.import=optional:file:secrets.properties

spring.datasource.url=${DB_URL:${db.url}}
spring.datasource.username=${DB_USERNAME:${db.username}}
spring.datasource.password=${DB_PASSWORD:${db.password}}


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.signing.key=${JWT_SECRET:${jwt.signing.key}}
jwt.expiration=${JWT_EXPIRATION:${jwt.expiration}}

# Upload paths
upload.folder=uploads
upload.path=${upload.folder}/

upload.albums.path=${upload.path}albums/
upload.albums.url=/uploads/albums/

upload.tracks.path=${upload.path}tracks/
upload.tracks.url=/uploads/tracks/

upload.playlists.path=${upload.path}playlists/
upload.playlists.url=/uploads/playlists/

# File upload settings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Static resources
spring.web.resources.static-locations=file:${upload.path}