spring.application.name=music
spring.config.import=file:secrets.properties

# PostgreSQL Configuration
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

upload.path=uploads/

# Размер файла (для загрузки)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Настройка для отдачи статики
spring.web.resources.static-locations=file:${upload.path}